var apparelData = [
    {
        name: "Bowler Hat",
        description: "A good-looking hat which projects a slightly urban, money-loving style. Improves social impact.",
        imageURL: "https://rimworldwiki.com/images/1/13/BowlerHat.png",
        type: "Apparel",
        subtype: "Clothing",
        isDLC: "false",
        clothingType: "Headgear",
        researchRequirement: ["Complex Clothing"],
        special: "+15% Social Impact",
        fabric: "true",
        leathery: "false",
        equipDelay: 0.8,
        protection_sharp: 20,
        protection_blunt: 20,
        protection_heat: 20,
        insulation_heat: 40,
        insulation_cold: 10,
        coverage: ["Head", "Left Ear", "Right Ear"],
        layer: "Overhead",
        workToMake: 30,
        resourcesToMake: {"Cloth": 20},
        marketValue: 70,
    },
    {
        name: "Coronet",
        description: "A tiny crown-like piece of headwear made of metal. It marks the wearer as a noble with stature.",
        imageURL: "https://rimworldwiki.com/images/b/b7/Coronet.png",
        type: "Apparel",
        subtype: "Clothing",
        isDLC: "true",
        clothingType: "Headgear",
        researchRequirement: ["Royal Apparel", "Complex Clothing", "Smithing"],
        special: "+20% Social Impact",
        fabric: "false",
        leathery: "false",
        protection_sharp: 0,
        protection_blunt: 0,
        protection_heat: 0,
        insulation_heat: 0,
        insulation_cold: 0,
        coverage: ["Head", "Left Ear", "Right Ear"],
        layer: "Overhead",
        workToMake: 134,
        resourcesToMake: {"Building Materials": 50},
        marketValue: 123
    }
]