var weaponsData = [
    {
        name: "Assault Rifle",
        description: "A general-purpose gas-operated assault rifle for field or urban combat. It has good range, decent power, and good accuracy.",
        imageURL: "https://rimworldwiki.com/images/e/e0/Assault_Rifle.png",
        type: "Equipment",
        subtype: "Weapons",
        class: "Industrial",
        mode: "Burst",
        damage: 11,
        armorPenetration: 16,
        stoppingPower: 0.5,
        warmup: 60,
        cooldown: 102,
        range: 30.9,
        burstCount: 3,
        burstTickInterval: 10,
        bulletSpeed: 70,
        accuracy_touch: 60,
        accuracy_short: 70,
        accuracy_medium: 65,
        accuracy_long: 55,
        missRadius: null,
        blastRadius: null,
        dps_optimal: 10.88,
        dps_touch: 6.528,
        dps_short: 7.616,
        dps_medium: 7.072,
        dps_long: 5.984,
        marketValue: 480
    }
]